name: PHP Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  PHP-70:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    
    - name: Setup PHP environment
      uses: nanasess/setup-php@v3.0.6
      with:
        php-version: 7.0

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Update Composer
      run: sudo composer self-update
      
    - name: Install Composer packages
      run: composer install --no-interaction --prefer-source --dev
    
    - name: Run PHPUnit
      run: ./vendor/bin/phpunit --configuration ./phpunit.xml.dist
      
    - name: Download Scrutinizer-CI
      run: wget https://scrutinizer-ci.com/ocular.phar
      
    - name: Run Code Coverage
      run: php ocular.phar code-coverage:upload --format=php-clover ./build/coverage/log/coverage.xml

  PHP-71:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    
    - name: Setup PHP environment
      uses: nanasess/setup-php@v3.0.6
      with:
        php-version: 7.1

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Update Composer
      run: sudo composer self-update
      
    - name: Install Composer packages
      run: composer install --no-interaction --prefer-source --dev
    
    - name: Run PHPUnit
      run: ./vendor/bin/phpunit --configuration ./phpunit.xml.dist
      
    - name: Download Scrutinizer-CI
      run: wget https://scrutinizer-ci.com/ocular.phar
      
    - name: Run Code Coverage
      run: php ocular.phar code-coverage:upload --format=php-clover ./build/coverage/log/coverage.xml

  PHP-72:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    
    - name: Setup PHP environment
      uses: nanasess/setup-php@v3.0.6
      with:
        php-version: 7.2

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Update Composer
      run: sudo composer self-update
      
    - name: Install Composer packages
      run: composer install --no-interaction --prefer-source --dev
    
    - name: Run PHPUnit
      run: ./vendor/bin/phpunit --configuration ./phpunit.xml.dist
      
    - name: Download Scrutinizer-CI
      run: wget https://scrutinizer-ci.com/ocular.phar
      
    - name: Run Code Coverage
      run: php ocular.phar code-coverage:upload --format=php-clover ./build/coverage/log/coverage.xml

  PHP-73:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    
    - name: Setup PHP environment
      uses: nanasess/setup-php@v3.0.6
      with:
        php-version: 7.3

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Update Composer
      run: sudo composer self-update
      
    - name: Install Composer packages
      run: composer install --no-interaction --prefer-source --dev
    
    - name: Run PHPUnit
      run: ./vendor/bin/phpunit --configuration ./phpunit.xml.dist
      
    - name: Download Scrutinizer-CI
      run: wget https://scrutinizer-ci.com/ocular.phar
      
    - name: Run Code Coverage
      run: php ocular.phar code-coverage:upload --format=php-clover ./build/coverage/log/coverage.xml

  PHP-74:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    
    - name: Setup PHP environment
      uses: nanasess/setup-php@v3.0.6
      with:
        php-version: 7.4

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Update Composer
      run: sudo composer self-update
      
    - name: Install Composer packages
      run: composer install --no-interaction --prefer-source --dev
    
    - name: Run PHPUnit
      run: ./vendor/bin/phpunit --configuration ./phpunit.xml.dist
      
    - name: Download Scrutinizer-CI
      run: wget https://scrutinizer-ci.com/ocular.phar
      
    - name: Run Code Coverage
      run: php ocular.phar code-coverage:upload --format=php-clover ./build/coverage/log/coverage.xml

  PHP-80:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    
    - name: Setup PHP environment
      uses: nanasess/setup-php@v3.0.6
      with:
        php-version: 8.0

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Update Composer
      run: sudo composer self-update
      
    - name: Install Composer packages
      run: composer install --no-interaction --prefer-source --dev
    
    - name: Run PHPUnit
      run: ./vendor/bin/phpunit --configuration ./phpunit.xml.dist
      
    - name: Download Scrutinizer-CI
      run: wget https://scrutinizer-ci.com/ocular.phar
      
    - name: Run Code Coverage
      run: php ocular.phar code-coverage:upload --format=php-clover ./build/coverage/log/coverage.xml
